version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: gulp-mocha
    versions:
    - 7.0.2
